run:
  timeout: 5m
  tests: true
  concurrency: 8

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - goconst
    - prealloc
    - bodyclose
    - sqlclosecheck

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting

  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: true
