version: '2'

run:
  timeout: 5m
  tests: true
  concurrency: 8

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - goconst
    - prealloc
    - bodyclose

formatters:
  enable:
    - gofmt
    - goimports